export const SIGN_UP ="SIGN_UP";
export const SIGN_UP_SUCCESS ="SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL ="SIGN_UP_FAIL";

export const LOG_IN ="LOG_IN";
export const LOG_IN_SUCCESS ="LOG_IN_SUCCESS";
export const LOG_IN_FAIL ="LOG_IN_FAIL";

export const OTP ="OTP";
export const OTP_SUCCESS ="OTP_SUCCESS";
export const OTP_FAIL ="OTP_FAIL";

export const PASSWORD_UPDATE ="PASSWORD_UPDATE";
export const PASSWORD_UPDATE_SUCCESS ="PASSWORD_UPDATE_SUCCESS";
export const PASSWORD_UPDATE_FAIL ="OTP_FAIL";

export const RESET_PASSWORD ="RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS ="RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL ="OTP_FAIL";


export const UPDATE_PROFILE ="UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS ="UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL ="UPDATE_PROFILE_FAIL";


export const GET_PRODUCT ="GET_PRODUCT";
export const GET_PRODUCT_SUCCESS ="GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL ="GET_PRODUCT_FAIL";


export const BANNER_LIST ="BANNER_LIST";
export const BANNER_LIST_SUCCESS ="BANNER_LIST_SUCCESS";
export const BANNER_LIST_FAIL ="GET_PRODUCT_FAIL";
